
package com.renho.internet.webservice.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2015-11-24T15:41:29.394+08:00
 * Generated source version: 2.6.10
 * 
 */
public final class TrainServiceHttpPost_TrainServiceHttpPost_Client {

    private static final QName SERVICE_NAME = new QName("Yangzhili", "TrainService");

    private TrainServiceHttpPost_TrainServiceHttpPost_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TrainService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TrainService ss = new TrainService(wsdlURL, SERVICE_NAME);
        TrainServiceHttpPost port = ss.getTrainServiceHttpPost();  
        
        {
        System.out.println("Invoking getTrainStationToStation...");
        java.lang.String _getTrainStationToStation_startStation = "";
        java.lang.String _getTrainStationToStation_arriveStation = "";
        java.lang.String _getTrainStationToStation_userId = "";
        com.renho.internet.webservice.cxf.ArrayOfTrainInfo _getTrainStationToStation__return = port.getTrainStationToStation(_getTrainStationToStation_startStation, _getTrainStationToStation_arriveStation, _getTrainStationToStation_userId);
        System.out.println("getTrainStationToStation.result=" + _getTrainStationToStation__return);


        }
        {
        System.out.println("Invoking getJsonTrainStationToStation...");
        java.lang.String _getJsonTrainStationToStation_startStation = "";
        java.lang.String _getJsonTrainStationToStation_arriveStation = "";
        java.lang.String _getJsonTrainStationToStation_userId = "";
        java.lang.String _getJsonTrainStationToStation__return = port.getJsonTrainStationToStation(_getJsonTrainStationToStation_startStation, _getJsonTrainStationToStation_arriveStation, _getJsonTrainStationToStation_userId);
        System.out.println("getJsonTrainStationToStation.result=" + _getJsonTrainStationToStation__return);


        }
        {
        System.out.println("Invoking getTrainDetailInfoByTrainNumber...");
        java.lang.String _getTrainDetailInfoByTrainNumber_trainNumber = "";
        java.lang.String _getTrainDetailInfoByTrainNumber_userId = "";
        com.renho.internet.webservice.cxf.ArrayOfTrainDetailInfo _getTrainDetailInfoByTrainNumber__return = port.getTrainDetailInfoByTrainNumber(_getTrainDetailInfoByTrainNumber_trainNumber, _getTrainDetailInfoByTrainNumber_userId);
        System.out.println("getTrainDetailInfoByTrainNumber.result=" + _getTrainDetailInfoByTrainNumber__return);


        }
        {
        System.out.println("Invoking getJsonDetailInfoByTrainNumber...");
        java.lang.String _getJsonDetailInfoByTrainNumber_trainNumber = "";
        java.lang.String _getJsonDetailInfoByTrainNumber_userId = "";
        java.lang.String _getJsonDetailInfoByTrainNumber__return = port.getJsonDetailInfoByTrainNumber(_getJsonDetailInfoByTrainNumber_trainNumber, _getJsonDetailInfoByTrainNumber_userId);
        System.out.println("getJsonDetailInfoByTrainNumber.result=" + _getJsonDetailInfoByTrainNumber__return);


        }

        System.exit(0);
    }

}
