server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://myserver:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root123
    hikari:
      minimum-idle: 5