spring:
  application:
    name: user-service
  zipkin:
    base-url: http://127.0.0.1:10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.150:8761/eureka/
server:
  port: 8763

