spring:
  application:
    name: user-service
  zipkin:
    base-url: http://127.0.0.1:10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://myserver:8761/eureka/
server:
  port: 8763
debug: true
