package com.renho;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-24T04:47:28.984Z
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "ReceiveImplService", 
                  wsdlLocation = "http://localhost:8080//webservice/Receive?wsdl",
                  targetNamespace = "http://renho.com/") 
public class ReceiveImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://renho.com/", "ReceiveImplService");
    public final static QName ReceiveImplPort = new QName("http://renho.com/", "ReceiveImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080//webservice/Receive?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReceiveImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080//webservice/Receive?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReceiveImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReceiveImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceiveImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReceiveImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReceiveImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReceiveImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Receive
     */
    @WebEndpoint(name = "ReceiveImplPort")
    public Receive getReceiveImplPort() {
        return super.getPort(ReceiveImplPort, Receive.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Receive
     */
    @WebEndpoint(name = "ReceiveImplPort")
    public Receive getReceiveImplPort(WebServiceFeature... features) {
        return super.getPort(ReceiveImplPort, Receive.class, features);
    }

}
