spring:
  application:
    name: oauth
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://myserver:3306/test?useSSL=false
    username: root
    password: root123
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
  redis:
    remote: true        #cachecloud 获取
    host: myserver
    port: 6379
    password:
    database: 1
server:
#  servlet:
#    context-path: /auth
  port: 8000
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.renho.auth.domain.po

urls:
  anon:
  - /authentication/**
  - /**/*.css
  - /social
  - /signin
  - /signup
  - /info
  - /health
  - /metrics/**
  - /loggers/**
  - /mobile/token
  - /login
debug: true
