ADFHOST2246="http://csdnim.allyes.com";
ADFCID2246=15;
ADFBID2246=2246;
ADFLOC='CNBJ0000';
ADFUSER2246="http://csdnim.allyes.com/c?d=csdnim&i=z15,10267148,2246,11409&rf=http%3A%2F%2Fblog.csdn.net%2Fcommon%2Fad.html%3Ft%3D4%26containerId%3Dad_cen%26frmId%3Dad_frm_0&a=dxBkZhmeh2A5yG7F6E35cevQ3&u=";
ALLYESID4="0980E6140D47A5F1";
ADFPGC="2,5,15,0,2978,2246,11409,10267148";

document.write("<script type='text/javascript'>\n");
document.write("var googletag = googletag || {};\n");
document.write("googletag.cmd = googletag.cmd || [];\n");
document.write("(function() {\n");
document.write("var gads = document.createElement('script');\n");
document.write("gads.async = true;\n");
document.write("gads.type = 'text/javascript';\n");
document.write("var useSSL = 'https:' == document.location.protocol;\n");
document.write("gads.src = (useSSL ? 'https:' : 'http:') + \n");
document.write("'//www.googletagservices.com/tag/js/gpt.js';\n");
document.write("var node = document.getElementsByTagName('script')[0];\n");
document.write("node.parentNode.insertBefore(gads, node);\n");
document.write("})();\n");
document.write("</Scr"+"ipt>\n");
document.write("\n");
document.write("<div id='div-gpt-ad-1429585234886-0'>\n");
document.write("<script type='text/javascript'>\n");
document.write("googletag.cmd.push(function() {\n");
document.write("googletag.defineSlot('/8456/IDG.CN_B2B_csdn.net', [728, 90], 'div-gpt-ad-1429585234886-0')\n");
document.write(".addService(googletag.pubads())\n");
document.write(".setTargeting(\"category\",\"blog\");\n");
document.write("googletag.enableServices();\n");
document.write("googletag.display('div-gpt-ad-1429585234886-0');\n");
document.write("});\n");
document.write("</Scr"+"ipt>\n");
document.write("</div>");

