spring:
  application:
    name: share
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://myserver:3306/test
    username: renho
    password: x
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
security:
  oauth2:
    client:
      client-id: r
      client-secret: rr
      scope: all
      access-token-uri: http://localhost:8000/oauth/token
      user-authorization-uri: http://localhost:8000/oauth/authorize
    resource:
      token-info-uri: http://localhost:8000/oauth/check_token
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.renho.share.domain.po
urls:
  anon:
  - /res/**
