spring:
  redis:
    host: myserver
    database: 1
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
server:
  port: 8000
urls:
  anon:
    - /authentication/**
    - /**/*.css
    - /social
    - /signin
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /mobile/token
    - /login
