spring:
  application:
    name: oauth
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://myserver:3306/test
    username: renho
    password: x
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
server:
#  servlet:
#    context-path: /auth
  port: 8000
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.renho.auth.domain.po
