spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myserver:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root123
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
sys:
  idgenerator:
#    db:
#      enabled: false
#      sequence_name: tttttt
#      start: 1
#      increment: 20
#      max: 99999999
    sf:
      enabled: true
#      bit: et
#      workerIdBits: 5
#      sequenceBits: 10
#      workerId: 21
      dynamicWorkId: true