server:
  port: 8080
renho:
  enabled: true
  name: renho-name
  #数据库连接地址，端口号，连接名，设置编码格式
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: com.renho.springbootcode.domain.pojo
  mapperLocations: classpath:mapper/*.xml
#logging:
#  path: /Users/renho/mlog
#  level:
#    root: debug
